version: "3"
services:
  tests:
    container_name: django_property_filter_test
    build:
      context: .
    working_dir: /project
    volumes:
      - .:/project
    depends_on:
      - postgresqldb
    command: sh -c /project/dev/run_tests_postgresql_local.sh

  postgresqldb:
    container_name: djangp_property_filter_postgresqldb
    image: postgres
    restart: always
    healthcheck:
      test: [“CMD-SHELL”, “pg_isready”]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - '5432:5432'
