[pycodestyle]
count = False
max-line-length = 120
statistics = True

ignore = E501, E722, W504
; E501 - Max Line Length, handled by Pylint
; E722 - do not use bare 'except', Already caught in pylint
; W504 - Break after binary Operator, clashing with W503

[tox]
; Mirror the testing of django-filter to ensure same compatability as good as possible
; Current tox Configuration in django filter
    ; {py310, py311, py312, py313}-django52,
    ; {py312, py313}-django60,
    ; {py312, py313}-latest,

envlist =
    ; All the combinations we claim to support
    {mylinux,mywindows}-{py310,py311,py312,py313,py314}-{django52}-{django_filter_23_5,django_filter_24_1,django_filter_24_2,django_filter_24_3,django_filter_25_1,django_filter_25_2,django_filter_latest}-{sqlite,postgres},
    {mylinux,mywindows}-{py312,py313,py314}-{django60}-{django_filter_23_5,django_filter_24_1,django_filter_24_2,django_filter_24_3,django_filter_25_1,django_filter_25_2,django_filter_latest}-{sqlite,postgres},
    {mylinux,mywindows}-{py312,py313,py314}-{django_latest}-{django_filter_latest}-{sqlite,postgres},

    ; Testing for what we have in our dev environment
    {mylinux,mywindows}-{py310,py311,py312,py313}-dev_latest-{sqlite,postgres},  # Special Configuration below

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
# Environment Variables to pass into tox
passenv =
    IS_CI_BUILD  # Used by Pytest to identify ci builds

allowlist_externals =
    /bin/sh
    sh
    dev\run_tests.bat
    set
    printenv
    cmd.exe

platform =
    mylinux: linux
    mywindows: win32

deps =
    django52: Django>=5.2,<6.0
    django60: Django>=6.0,<6.1 
    django_latest: django

    django_filter_23_5: django-filter==23.5
    django_filter_24_1: django-filter==24.1
    django_filter_24_2: django-filter==24.2
    django_filter_24_3: django-filter==24.3
    django_filter_25_1: django-filter==25.1
    django_filter_25_2: django-filter==25.2
    django_filter_latest: django-filter

    postgres: psycopg[binary,pool]

    # Specifying the pytest versions, so on future runs we don't run with later, untested versions
    # !!! These versions "MUST" match the ones in "requirements.txt"
    pytest==9.0.3
    pytest-cov==7.1.0
    pytest-django==4.12.0

commands_pre = # !!! Leave blank, to be overwritten in special sections below

commands =
    pip list
    mywindows: cmd.exe /C set  # In case running bash e.g. Git Bash from windows
    mylinux: printenv

    # We're passing in the DB to test against
    mywindows: dev\run_tests.bat {posargs}
    mylinux: sh -c './dev/run_tests.sh {posargs}'

[testenv:{mylinux,mywindows}-{py310,py311,py312,py313,py314}-dev_latest-{sqlite,postgres}]
deps =
    -rrequirements.txt

[testenv:{mylinux,mywindows}-{py310,py311,py312,py313,py314}-all_filter_volume_test-{sqlite,postgres}]
setenv = 
    ALL_FILTER_VOLUME_TEST = TRUE
deps =
    -rrequirements.txt
commands_pre =  # Uninstall psycopg which got installed by command "-rrequirements.txt"
    sqlite: pip uninstall -y psycopg psycopg-binary psycopg-pool

; Disable for Testing, if not failing can remove
; [testenv:{mylinux,mywindows}-{py37,py38,py39,py310,py311}-{django32,django40,django41}-{django_filter23,django_filter24,django_filter211,django_filter221,django_filter_latest}-{sqlite,postgres}]
; # Disable warnings for older (non supported) Django versions, Github actions failed because of deprecated warnings
; setenv = 
;     ENV_PYTEST_EXTRA_ARGS = -p no:warnings
