# Generated by Django 3.0.6 on 2020-06-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0002_delivery_deliveryline_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_true', models.BooleanField(null=True)),
            ],
        ),
    ]
