# Generated by Django 3.0.6 on 2020-06-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0003_booleanclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
