# Generated by Django 3.0.6 on 2020-06-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0004_textclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
