# Generated by Django 3.0.7 on 2020-06-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0005_dateclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
    ]
