# Generated by Django 3.0.7 on 2020-06-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0006_timeclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField()),
            ],
        ),
    ]
