# Generated by Django 3.0.7 on 2020-06-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0007_durationclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='durationclass',
            name='duration',
            field=models.DurationField(),
        ),
    ]
