# Generated by Django 3.0.7 on 2020-06-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0008_auto_20200615_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
