# Generated by Django 3.0.7 on 2020-06-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0009_datetimeclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateFromToRangeFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
