# Generated by Django 3.0.7 on 2020-06-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0010_datefromtorangefiltermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BooleanClass',
            new_name='BooleanFilterModel',
        ),
    ]
