# Generated by Django 3.0.7 on 2020-06-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0011_auto_20200624_1945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextClass',
            new_name='CharFilterModel',
        ),
    ]
