# Generated by Django 3.0.7 on 2020-06-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0012_auto_20200624_1948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DateClass',
            new_name='DateFilterModel',
        ),
    ]
