# Generated by Django 3.0.7 on 2020-06-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0013_auto_20200624_1949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DateTimeClass',
            new_name='DateTimeFilterModel',
        ),
    ]
