# Generated by Django 3.0.7 on 2020-06-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0014_auto_20200624_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DurationClass',
            new_name='DurationFilterModel',
        ),
    ]
