# Generated by Django 3.0.7 on 2020-06-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0015_auto_20200624_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
            ],
        ),
    ]
