# Generated by Django 3.0.7 on 2020-06-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0017_auto_20200624_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
    ]
