# Generated by Django 3.0.7 on 2020-06-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0020_datetimefromtorangefiltermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeRangeModel',
            new_name='TimeRangeFilterModel',
        ),
    ]
