# Generated by Django 3.0.7 on 2020-06-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0021_auto_20200625_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsoDateTimeFromToRangeFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
