# Generated by Django 3.0.7 on 2020-06-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0022_isodatetimefromtorangefiltermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsoDateTimeFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
