# Generated by Django 3.0.7 on 2020-06-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0023_isodatetimefiltermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UUIDFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
            ],
        ),
    ]
