# Generated by Django 3.0.7 on 2020-06-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0024_uuidfiltermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
            ],
        ),
    ]
