# Generated by Django 3.0.7 on 2020-07-04 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0026_typedchoicefiltermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typedchoicefiltermodel',
            old_name='truth',
            new_name='text',
        ),
    ]
