# Generated by Django 3.0.7 on 2020-07-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0027_auto_20200704_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllValuesFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
            ],
        ),
    ]
