# Generated by Django 3.0.7 on 2020-07-10 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0029_daterangefiltermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelChoiceFilterRelatedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ModelChoiceFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_models', to='property_filter.ModelChoiceFilterRelatedModel')),
            ],
        ),
    ]
