# Generated by Django 3.0.7 on 2020-07-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0030_modelchoicefiltermodel_modelchoicefilterrelatedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
            ],
        ),
    ]
