# Generated by Django 3.0.7 on 2020-07-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0031_multiplechoicefiltermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllValuesMultipleFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
            ],
        ),
    ]
