# Generated by Django 3.0.8 on 2020-07-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0033_typedmultiplechoicefiltermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupChoiceFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
            ],
        ),
    ]
