# Generated by Django 3.0.8 on 2020-07-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0034_lookupchoicefiltermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCSVFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('text', models.CharField(max_length=32)),
            ],
        ),
    ]
