# Generated by Django 3.0.8 on 2020-07-29 03:29

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0034_lookupchoicefiltermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericRangeFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', django.contrib.postgres.fields.ranges.IntegerRangeField(null=True)),
            ],
        ),
    ]
