# Generated by Django 3.0.8 on 2020-08-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0036_baseinfiltermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRangeFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
