# Generated by Django 3.0.8 on 2020-08-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0037_baserangefiltermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderingFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
            ],
        ),
    ]
