# Generated by Django 3.0.8 on 2020-08-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0039_doubleintmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_true', models.BooleanField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('text', models.CharField(max_length=32)),
            ],
        ),
    ]
