# Generated by Django 3.0.8 on 2020-09-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0043_benchmarktestmodel_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarktestmodel',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
