# Generated by Django 3.0.8 on 2020-09-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0044_benchmarktestmodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarktestmodel',
            name='iso_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarktestmodel',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarktestmodel',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarktestmodel',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
