# Generated by Django 3.0.8 on 2020-09-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0045_auto_20200903_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multifiltertestmodel',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='multifiltertestmodel',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
