# Generated by Django 3.0.8 on 2020-09-27 06:18

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0046_auto_20200911_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericRangeFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postgres_int_range', django.contrib.postgres.fields.ranges.IntegerRangeField()),
            ],
        ),
    ]
