# Generated by Django 3.0.8 on 2020-09-27 07:24

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0047_numericrangefiltermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericrangefiltermodel',
            name='postgres_int_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True),
        ),
    ]
