# Generated by Django 3.0.8 on 2020-10-09 04:01

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_filter', '0048_auto_20200927_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='numericrangefiltermodel',
            name='postgres_decimal_range',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True),
        ),
    ]
