name: 'Release to Test PyPi' # Name becomes part of the badge location

on:
  workflow_dispatch:


jobs:

  # Deployment job
  deployment:
    runs-on: ubuntu-latest
    name: TestPyPiDeployment
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Setup Env
        run: |
          pip --version
          python --version --version
          pip list
          python -m pip install --upgrade pip pipenv
          pip install build twine
          pip list
      - name: Create Wheel
        run: |
          ./dev/Packaging/create_wheel.sh
          echo Command: 'dir dist/*'
          dir dist/*
      - name: Check Wheel
        run: |
          ./dev/Packaging/check_wheels.sh
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          ### PyPy.Test settings
          repository-url: https://test.pypi.org/legacy/
          # Temp workaround since attestations are on by default as of gh-action-pypi-publish v1.11.0
          # https://github.com/pypa/gh-action-pypi-publish/issues/283
          # attestations: false
          verbose: true
